// Generated by Rcpp::compileAttributes() style registration.
// Manual wrappers are committed so source installs can compile without an
// attribute-generation step.

#include <Rcpp.h>

using namespace Rcpp;

// sby_table_internal_detect_integer_type
NumericVector sby_table_internal_detect_integer_type(IntegerVector current_column);
RcppExport SEXP _sbyops_sby_table_internal_detect_integer_type(SEXP current_columnSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RObject rcpp_current_column(current_columnSEXP);
  rcpp_result_gen = Rcpp::wrap(
    sby_table_internal_detect_integer_type(Rcpp::as<Rcpp::IntegerVector>(rcpp_current_column))
  );
  return rcpp_result_gen;
  END_RCPP
}

// sby_table_internal_detect_numeric_type
NumericVector sby_table_internal_detect_numeric_type(NumericVector current_column);
RcppExport SEXP _sbyops_sby_table_internal_detect_numeric_type(SEXP current_columnSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RObject rcpp_current_column(current_columnSEXP);
  rcpp_result_gen = Rcpp::wrap(
    sby_table_internal_detect_numeric_type(Rcpp::as<Rcpp::NumericVector>(rcpp_current_column))
  );
  return rcpp_result_gen;
  END_RCPP
}
