# Generated by Rcpp::compileAttributes() style registration.
# Manual wrapper definitions are kept in-repository so source installs do not
# need to regenerate them before compilation.

sby_table_internal_detect_integer_type <- function(current_column) {
  .Call(
    "_sbyops_sby_table_internal_detect_integer_type",
    current_column,
    PACKAGE = "sbyops"
  )
}

sby_table_internal_detect_numeric_type <- function(current_column) {
  .Call(
    "_sbyops_sby_table_internal_detect_numeric_type",
    current_column,
    PACKAGE = "sbyops"
  )
}
