# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Detect Integer Vector Metadata for Arrow Schema Optimization
#'
#' @description
#' Performs a single-pass scan over an integer vector to collect metadata
#' required for efficient Apache Arrow type inference.
#'
#' @details
#' This function avoids separate calls for minimum, maximum, and boolean
#' feasibility checks on integer columns. In a single pass over the vector, it
#' evaluates whether the column has valid values, whether all valid values can
#' be represented as booleans, and what the minimum and maximum values are.
#'
#' Missing values are ignored. Since the input vector is already an integer
#' vector in R, no fractional component check is required.
#'
#' The function returns an unnamed numeric vector to reduce allocations at the
#' C++ and R interface. The positions must be interpreted as follows:
#' \enumerate{
#'   \item Presence of at least one non-missing value
#'   \item Boolean representation feasibility
#'   \item Minimum value
#'   \item Maximum value
#' }
#'
#' @param current_column Integer vector from R.
#'
#' @return Numeric vector with four positions.
#'
#' @usage sby_internal_table_detect_integer_type(current_column)
#'
#' @keywords internal
NULL

sby_internal_table_detect_integer_type <- function(current_column) {
    .Call(`_sbyops_sby_internal_table_detect_integer_type`, current_column)
}

#' @title Detect Numeric Vector Metadata for Arrow Schema Optimization
#'
#' @description
#' Performs a single-pass scan over a numeric vector to collect metadata
#' required for efficient Apache Arrow type inference.
#'
#' @details
#' This function is intended for internal use in high-performance Parquet
#' writing routines. In a single pass over the vector, it evaluates whether
#' the column has valid values, whether it contains non-finite values, whether
#' all finite values are mathematical integers, whether all finite values can
#' be represented as numeric booleans, and what the minimum and maximum finite
#' values are.
#'
#' Missing values, including \code{NA} and \code{NaN}, are ignored. Infinite
#' values are detected and prevent safe conversion to integer Arrow types.
#'
#' The function returns an unnamed numeric vector to reduce allocations at the
#' C++ and R interface. The positions must be interpreted as follows:
#' \enumerate{
NULL

#'   \item Presence of at least one non-finite value
NULL

#'   \item Boolean representation feasibility
NULL

#'   \item Maximum finite value
NULL

#'
NULL

#'
NULL

#'
NULL

#'
NULL

sby_internal_table_detect_numeric_type <- function(current_column) {
    .Call(`_sbyops_sby_internal_table_detect_numeric_type`, current_column)
}
