# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Detectar metadados de vetor inteiro para esquema Arrow
#' @usage sby_internal_table_detect_integer_type(current_column)
#' @description
#' Encapsula a rotina C++ que examina um vetor inteiro em uma passagem para
#' apoiar a inferência interna de tipos Arrow usada na escrita Parquet.
#'
#' @details
#' A função existe como wrapper gerado por Rcpp para a chamada nativa registrada.
#' Valores ausentes são ignorados pela implementação C++. O retorno é um vetor
#' numérico sem nomes, cuja posição indica presença de valor válido, viabilidade
#' booleana, mínimo e máximo. A função não altera o vetor de entrada, não acessa
#' banco de dados, não lê arquivos e não grava arquivos.
#'
#' @param current_column Vetor inteiro recebido do R.
#'
#' @return Vetor numérico de quatro posições retornado pela rotina C++.
#'
#' @seealso sby_table_optimize_scheme
#' @keywords internal
sby_internal_table_detect_integer_type <- function(current_column) {
    .Call(`_sbyops_sby_internal_table_detect_integer_type`, current_column)
}

#' @title Detectar metadados de vetor numérico para esquema Arrow
#' @usage sby_internal_table_detect_numeric_type(current_column)
#' @description
#' Encapsula a rotina C++ que examina um vetor numérico em uma passagem para
#' apoiar a inferência interna de tipos Arrow usada na escrita Parquet.
#'
#' @details
#' A função existe como wrapper gerado por Rcpp para a chamada nativa registrada.
#' A implementação ignora NA e NaN, sinaliza valores infinitos e informa se os
#' valores finitos podem ser tratados como inteiros ou booleanos. O retorno é um
#' vetor numérico sem nomes com presença de valor analisável, presença de não
#' finitos, viabilidade inteira, viabilidade booleana, mínimo finito e máximo
#' finito. A função não altera o vetor de entrada.
#'
#' @param current_column Vetor numérico recebido do R.
#'
#' @return Vetor numérico de seis posições retornado pela rotina C++.
#'
#' @seealso sby_table_optimize_scheme
#' @keywords internal
sby_internal_table_detect_numeric_type <- function(current_column) {
    .Call(`_sbyops_sby_internal_table_detect_numeric_type`, current_column)
}
