#' @title Internal Helper: Compute Correlation BLAS
#'
#' @usage sby_internal_compute_correlation_blas(mat)
#'
#' @description
#' Compute an absolute Pearson correlation matrix using centered linear
#' algebra operations accelerated by BLAS backends
#'
#' @details
#' The function centers columns, computes covariance through
#' `crossprod`, and normalizes by outer products of column norms
#'
#' @section Mathematical reference:
#' Let \eqn{X_c} be the centered matrix. The covariance is computed as
#' \eqn{X_c^\top X_c}, and normalization uses
#' \eqn{\sqrt{d_i d_j}} with \eqn{d_i = \sum_k X_{c,ki}^2}
#'
#' @param mat A numeric matrix used for correlation estimation
#'
#' @return A square absolute-correlation matrix with sanitized entries
#'
#' @seealso [sby_select_correlation()]
#'
#' @references
#' R CORE TEAM. Writing R Extensions. Vienna: R Foundation.
#' \href{https://cran.r-project.org/doc/manuals/r-release/R-exts.html}{R Extensions Manual}
#'
#' @examples
#' example_matrix <- matrix(rnorm(20), ncol = 4)
#' sby_internal_compute_correlation_blas(mat = example_matrix)
sby_internal_compute_correlation_blas <- function(mat){

  # Compute centered data for covariance estimation
  column_means <- colMeans(mat)
  centered_matrix <- sweep(mat, 2L, column_means, FUN = "-")

  # Compute column norms used in correlation normalization
  sum_squares <- colSums(centered_matrix * centered_matrix)

  # Compute covariance matrix through matrix multiplication
  covariance_matrix <- crossprod(centered_matrix)

  # Build denominator matrix for Pearson normalization
  denominator_matrix <- sqrt(outer(sum_squares, sum_squares))

  # Convert covariance values to absolute correlations
  correlation_matrix <- abs(covariance_matrix / denominator_matrix)

  # Replace non-finite values generated by degenerate columns
  correlation_matrix[!is.finite(correlation_matrix)] <- 0

  # Clear diagonal to simplify threshold-based pruning logic
  diag(correlation_matrix) <- 0

  # Return absolute-correlation matrix for downstream selection
  return(correlation_matrix)
}
####
## End
# 
